### ISSUE TITLE
chatbot

### ISSUE THREAD

**Issue by Vanshika1021** [amittri1025/Whatsapp-Link-Gen#10]
Add a popup chatbot for help and more usefulness

**Comment by amittri1025** [comment]
@Vanshika1021 Yes you can go for it. Assigned.

**Comment by amittri1025** [comment]
@Vanshika1021 are you working on it ?

**Comment by Vanshika1021** [comment]
Yes but i still. Want some help regarding it
This is my first contribution

**Comment by amittri1025** [comment]
@Vanshika1021 Kindly tell me your tech stack

**Comment by Vanshika1021** [comment]
I'm a begginer in  coding and hence know very few things only
I just not able to fix things right
But can help in finding out them
I haven't assigned any issue instead of yours

**Comment by amittri1025** [comment]
@Vanshika1021 Doesn't matter you could still start contributing. 
If you require any help kindly reach me out https://www.linkedin.com/in/tripathiamit10/

**Comment by amittri1025** [comment]
@Vanshika1021 are you interested or should I close this issue 😊

**Comment by amittri1025** [comment]
Great...
