### ISSUE TITLE
Option to Add Emojis in Text to send

### ISSUE THREAD

**Issue by amittri1025** [amittri1025/Whatsapp-Link-Gen#13]
In the Text Input there should be a button sort of thing to include emojis in the message.
![image](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/74503582/23943f0e-978e-428a-aa2f-7bf8f3b666aa)

**Comment by VIVEKIITdelhi** [comment]
I can do this, you may assign it to me.....

**Comment by pushkaraj2007** [comment]
Hey @amittri1025 

I would like to work on this issue. Can you please assign this to me?

**Comment by amittri1025** [comment]
Yupp @pushkaraj2007

**Comment by amittri1025** [comment]
@vaanyasharmaaa would you like to work upon this, since the above user is unavailable.

**Comment by pushkaraj2007** [comment]
No, @amittri1025!

I'm available, I have started working on this issue, I'll submit a PR by tomorrow!
