### ISSUE TITLE
Back to Top Button

### ISSUE THREAD

**Issue by amittri1025** [amittri1025/Whatsapp-Link-Gen#18]
Add a Back to Top Button, on the Home Page, 

Take Inspiration , Background should match with page theme.
![image](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/74503582/4c5775c4-242d-4946-9931-d86ee87bb6cb)

**Comment by sayyedarib** [comment]
can you please assign this issue to me?

**Comment by ani-netizen** [comment]
Hey @amittri1025 

I can help you with it I have already dealt with similar thing previously. Kindly assign this to me 
Thank you

**Comment by shubhampr07** [comment]
hey, please assign this issue to me

**Comment by amittri1025** [comment]
@sayyedarib start working on it.

**Comment by senpa1-13** [comment]
added pull request for the issue

**Comment by amittri1025** [comment]
@senpa1-13
improve the styling. it should be position : absolute and z-index : 999, 
Also , Do not add Text, just a chevron with a nice green background would be enough.

**Comment by amittri1025** [comment]
@senpa1-13 fix the back to top button, it's not properly aligned.
