### ISSUE TITLE
Build Sign-in/Sign-Up Page

### ISSUE THREAD

**Issue by Shruti0316** [amittri1025/Whatsapp-Link-Gen#19]
In the current header there's is sign-in and sign-up option but no specific page for it. I would like to work on it and build the required page.
My current idea is as follows: 
For Signup page we can have Name, email, phone number, password, confirm password fields.
For Sign-in we can have email/phone number , password and if required add re captcha also.

Any feedback from your side is appreciated, Please assign this issue to me so that I can start working on it.
Thanks

**Comment by amittri1025** [comment]
@Shruti0316 yes , actually those pages do not have much use here, kindly remove them.
You should work on #16
