### ISSUE TITLE
Update the copyright section

### ISSUE THREAD

**Issue by amittri1025** [amittri1025/Whatsapp-Link-Gen#4]
Update it to 2023
![image](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/74503582/fba28168-e6f0-4939-9688-3a169f112172)

**Comment by Himral** [comment]
@amittri1025  Assign me this issue

**Comment by Mounikakasa72** [comment]
@amrittri1025
 can u please assign this issue

**Comment by ainaagnihotri** [comment]
@amittri1025 can u please assign this issue to me

**Comment by amittri1025** [comment]
Done @mounika7204 since you were the first one to ask.

**Comment by amittri1025** [comment]
yes  @mounika7204

**Comment by amittri1025** [comment]
#11 Done

**Comment by mounika7204** [comment]
This is my first ever contribution.Thanks for helping me out.
