### ISSUE TITLE
Fix the Mobile Menu

### ISSUE THREAD

**Issue by amittri1025** [amittri1025/Whatsapp-Link-Gen#44]
Remove Pages Link Blog, Sign In, Sign Up

![image](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/74503582/1cf02f91-5b7b-40c2-b6b4-4bc9d4e7d960)

**Comment by amittri1025** [comment]
@PranavBarthwal You can work upon it.

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, Can you assign me?

**Comment by senpa1-13** [comment]
Can I work on this?
