### ISSUE TITLE
Overflow issues on contact page

### ISSUE THREAD

**Issue by Bsodoge** [amittri1025/Whatsapp-Link-Gen#52]
As can be seen below there is overflow on the y axis of the contact page.

![image](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/79531561/faf689b5-92ce-4c5b-be4b-4ce6c0989a31)

I would like to solve this issue, please assign this issue to me under hacktoberfest

**Comment by amittri1025** [comment]
Good. Fix it. and also remove unneccessary pages missed in #50

**Comment by amittri1025** [comment]
fixed in #54
