### ISSUE TITLE
[UI]: Generate link button not visible

### ISSUE THREAD

**Issue by sanjeevani-25** [amittri1025/Whatsapp-Link-Gen#68]
Please assign me this under hacktoberfest. I'll redesign the button same as it was previously(shown in README file).

![image](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/96921605/2a9bf1a1-f92e-4745-ace9-d721ce2e914a)

**Comment by amittri1025** [comment]
start working on it. make sure to put screen recording in PR

**Comment by MKisKrazy** [comment]
> start working on it. make sure to put screen recording in PR

it seems like the generate link works fine for me :)

**Comment by sanjeevani-25** [comment]
I was talking about the UI of button, the button works fine but it's not visible. It has grey color with border radius so large that it doesn't look like call-to-action button.

**Comment by sanjeevani-25** [comment]
Sure I'll work on it @amittri1025
