### ISSUE TITLE
Replace Dark Mode Button with Icon Button Toggle

### ISSUE THREAD

**Issue by amittri1025** [amittri1025/Whatsapp-Link-Gen#70]
Replace the current textual button with an Icon Based Toggle. 

Inspiration : 
![image](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/74503582/8da81f4d-b98d-4a5a-b2ab-3c1e75dc329e)

Make sure to put Screen Recording of Working :)

**Comment by KriteshTimsina** [comment]
@amittri1025  I'll take this!
