### ISSUE TITLE
Creating a Country Operator Option on Mobile Number Input.

### ISSUE THREAD

**Issue by amittri1025** [amittri1025/Whatsapp-Link-Gen#8]
Currently this Web App could be used by Indian users only, because I have hard coded a 91 in API used to generate the Link.
![image](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/74503582/1673d1c8-d4e3-4c5a-ab03-679cc05ab210)

Create a Input Type Dropdown with different Country Codes and Flags to be used in the API

**Comment by amittri1025** [comment]
@ritik48 would you like to work upon this.

**Comment by ritik48** [comment]
@amittri1025 yes sure, but just wanted to know this project is not in gssoc right ?

**Comment by amittri1025** [comment]
Yes, ofc, just a practice project
