### ISSUE TITLE
Bug: contact page is not responsive

### ISSUE THREAD

**Issue by accodes21** [amittri1025/Whatsapp-Link-Gen#81]
The contact page is not responsive and the boxes are overflowing.
I would like to work on it.
 Screenshot: 
![Screenshot_20231010_073759_Chrome](https://github.com/amittri1025/Whatsapp-Link-Gen/assets/101868279/ddd23b7d-f8ad-4253-a859-f61df35e2fc4)

**Comment by Anniebhalla10** [comment]
I would like to work on this issue.
Could you please assign this to me.
@accodes21

**Comment by Raman01010010** [comment]
please assign it to me

**Comment by coder483** [comment]
i created a pull request and fixed the contact page responsiveness you can check and merge it

**Comment by accodes21** [comment]
@coder483 since this was assigned to me you cannot work on it because it goes against the values of Open Source
