### ISSUE TITLE
Need hovering effect on buttons and by adding some slight text shadow makes the website more beautiful.

### ISSUE THREAD

**Issue by Ananta2545** [amittri1025/Whatsapp-Link-Gen#82]
Want to add hovering effect on buttons.   (Maintaining responsiveness and theme of the website).
Want to add suitable text shadow to beautify the website.
A slight animation to some headers and paragraph.

This all changes i want to do by maintaining the responsiveness and theme of the website. Thanks.

**Comment by Arnav7107** [comment]
Hi @Ananta2545, I would love to try to add the said features. Can you please assign it to me?

**Comment by Ananta2545** [comment]
Extremely sorry @Arnav7107  I have already add the above features. But you can add text shadow and make the website more attractive. Please keep the website responsive.
